### PR TITLE
Fixed compatibility with `guzzlehttp/psr7:^2.0`

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by gmponos** [comment]
Thank you

**Comment by MiguelAlcaino** [comment]
Hi @gmponos . Could you please create a new tag version to have it updated on packagist?
Thanks

**Comment by GrahamCampbell** [comment]
Not necessarily, because of the branch alias. https://github.com/gmponos/guzzle-log-middleware/blob/master/composer.json#L52

**Comment by GrahamCampbell** [comment]
You can still use nice version constraints, to the the version you need.

**Comment by MiguelAlcaino** [comment]
Sure @GrahamCampbell . But it would be still nice to have `v2.0.1` to include this change that we know does not break anything. And it would be easier to update with `composer update gmponos/guzzle_logger`

**Pull request merged**
